/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documentsUpdate } from "../../funcs/documentsUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DocumentSetSettingsForDocumentRequestBody$inboundSchema,
};

export const tool$documentsUpdate: ToolDefinition<typeof args> = {
  name: "documents_update",
  description: `Update document`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await documentsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
