/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documentsRedistribute } from "../../funcs/documentsRedistribute.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DocumentResendDocumentRequestBody$inboundSchema,
};

export const tool$documentsRedistribute: ToolDefinition<typeof args> = {
  name: "documents_redistribute",
  description: `Redistribute document

Redistribute the document to the provided recipients who have not actioned the document. Will use the distribution method set in the document`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await documentsRedistribute(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
