/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documentsRecipientsUpdate } from "../../funcs/documentsRecipientsUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RecipientUpdateDocumentRecipientRequestBody$inboundSchema,
};

export const tool$documentsRecipientsUpdate: ToolDefinition<typeof args> = {
  name: "documents-recipients_update",
  description: `Update document recipient

Update a single recipient for a document.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await documentsRecipientsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
