/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documentsRecipientsCreateMany } from "../../funcs/documentsRecipientsCreateMany.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.RecipientCreateDocumentRecipientsRequestBody$inboundSchema,
};

export const tool$documentsRecipientsCreateMany: ToolDefinition<typeof args> = {
  name: "documents-recipients_create-many",
  description: `Create document recipients

Create multiple recipients for a document.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await documentsRecipientsCreateMany(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
