/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documentsRecipientsUpdateMany } from "../../funcs/documentsRecipientsUpdateMany.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.RecipientUpdateDocumentRecipientsRequestBody$inboundSchema,
};

export const tool$documentsRecipientsUpdateMany: ToolDefinition<typeof args> = {
  name: "documents-recipients_update-many",
  description: `Update document recipients

Update multiple recipients for a document.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await documentsRecipientsUpdateMany(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
