/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { templatesFieldsGet } from "../../funcs/templatesFieldsGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.FieldGetTemplateFieldRequest$inboundSchema,
};

export const tool$templatesFieldsGet: ToolDefinition<typeof args> = {
  name: "templates-fields_get",
  description: `Get template field

Returns a single field. If you want to retrieve all the fields for a template, use the "Get Template" endpoint.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await templatesFieldsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
