/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { templatesFieldsCreate } from "../../funcs/templatesFieldsCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.FieldCreateTemplateFieldRequestBody$inboundSchema,
};

export const tool$templatesFieldsCreate: ToolDefinition<typeof args> = {
  name: "templates-fields_create",
  description: `Create template field

Create a single field for a template.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await templatesFieldsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
