/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { templatesDirectLinkToggle } from "../../funcs/templatesDirectLinkToggle.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.TemplateToggleTemplateDirectLinkRequestBody$inboundSchema,
};

export const tool$templatesDirectLinkToggle: ToolDefinition<typeof args> = {
  name: "templates-direct-link_toggle",
  description: `Toggle direct link

Enable or disable a direct link for a template`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await templatesDirectLinkToggle(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
