/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { templatesFieldsUpdate } from "../../funcs/templatesFieldsUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.FieldUpdateTemplateFieldRequestBody$inboundSchema,
};

export const tool$templatesFieldsUpdate: ToolDefinition<typeof args> = {
  name: "templates-fields_update",
  description: `Update template field

Update a single field for a template.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await templatesFieldsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
