/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { templatesDuplicate } from "../../funcs/templatesDuplicate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.TemplateDuplicateTemplateRequestBody$inboundSchema,
};

export const tool$templatesDuplicate: ToolDefinition<typeof args> = {
  name: "templates_duplicate",
  description: `Duplicate template`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await templatesDuplicate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
