/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { templatesFind } from "../../funcs/templatesFind.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.TemplateFindTemplatesRequest$inboundSchema,
};

export const tool$templatesFind: ToolDefinition<typeof args> = {
  name: "templates_find",
  description: `Find templates

Find templates based on a search criteria`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await templatesFind(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
