/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { templatesRecipientsCreate } from "../../funcs/templatesRecipientsCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RecipientCreateTemplateRecipientRequestBody$inboundSchema,
};

export const tool$templatesRecipientsCreate: ToolDefinition<typeof args> = {
  name: "templates-recipients_create",
  description: `Create template recipient

Create a single recipient for a template.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await templatesRecipientsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
