/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { templatesUse } from "../../funcs/templatesUse.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.TemplateCreateDocumentFromTemplateRequestBody$inboundSchema,
};

export const tool$templatesUse: ToolDefinition<typeof args> = {
  name: "templates_use",
  description: `Use template

Use the template to create a document`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await templatesUse(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
