/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { templatesRecipientsUpdateMany } from "../../funcs/templatesRecipientsUpdateMany.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.RecipientUpdateTemplateRecipientsRequestBody$inboundSchema,
};

export const tool$templatesRecipientsUpdateMany: ToolDefinition<typeof args> = {
  name: "templates-recipients_update-many",
  description: `Update template recipients

Update multiple recipients for a template.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await templatesRecipientsUpdateMany(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
